### ISSUE TITLE
Permissions Error

### ISSUE THREAD

**Issue by paulnordlund** [LeadPages/LeadPagesYeoman#9]
Hi LeadPages Representative,

I'm having an issue with system permissions related to installing npm modules (see output below).  Any advice?  

Thanks much,
Paul

paulnorlundsmbp:LeadPages paulnordlund$ npm install -g yo generator-leadpages gulp
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo" "generator-leadpages" "gulp"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /usr/local/bin/yo
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/local/bin/yo'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/bin/yo'] errno: -13, code: 'EACCES', path: '/usr/local/bin/yo' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/bin/yo'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/bin/yo'] errno: -13, code: 'EACCES', path: '/usr/local/bin/yo' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/paulnordlund/Desktop/Paul's Code/LeadPages/npm-debug.log
paulnorlundsmbp:LeadPages paulnordlund$ sudo gulp start
sudo: gulp: command not found

**Comment by supawaza** [comment]
Hi, on our readme, there is instructions how to get rid of this. You can simply just do this:

If you receive an error relating to permissions, here are some additional options:
Run **sudo chown -R `whoami` ~/.npm** to fix a potential permission issue. (Note: ' around whoami are the grave accent ), then trynpm install -g yo generator-leadpages` again.

If that still doesn't work, try **sudo chown -R `whoami` /usr/local/lib/node_modules** (Note: ' around whoami are the grave accent ), then trynpm install -g yo generator-leadpages`

If that still doesn't work, try **sudo npm install -g yo generator-leadpages** in front and enter your password.
If you're still having problems, submit an issue here.
